### ISSUE TITLE
html 작성

### ISSUE THREAD

**Issue by wlsud801** [jisung24/six_online#1]
제가 디자인은 임의로 해봤는데 하면서 더 다듬고 수정하면 될 것 같습니다.

각 화면의 파일은 이렇게 참고하시면 됩니다. 
1. 회원가입, 로그인 : login.html
2. 사용자 검색 화면, 관리자 검색 & 리스트 화면 : index.html
3. 관리자 선수 edit 상세 화면 : register.html

common.js 파일의 스크립트는 아직 작성 중입니다.

확인하시고 궁금하신 것 있으면 말해주세요~

**Comment by jisung24** [comment]
네 내일 ㅎ학인하겠습니다!
감사드립니다ㅎㅎ
